export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SET_SELECTED_CATEGORIES = 'SET_SELECTED_CATEGORIES';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';